version: "2"
services:
  prez:
    image: ameausoone/docker-image-asciidoctor-reveal.js
    ports:
      - "9000:8000"
    volumes:
      - ./slides/:/opt/slides/
      - ./docs/:/opt/output/
    environment:
      INDEX: coverage-and-mutation-testing.html
