= Grupo 03 - MBA FIAP
:backend: revealjs
:revealjs_history: true
:revealjsdir: https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.4.1
:revealjs_theme: black
:source-highlighter: highlightjs
:imagesdir: images
:revealjs_transition: convex
:revealjs_plugin_zoom: enabled
:customcss: customcss.css

==  Integrantes do grupo
* Alexandre Sato
* Filipe Andreato
* Joaquim de Santana Francisco
* Jorge Takeshi Sato

== Segmentos: 
* Segmento: Saúde
* Sub-Segmento: Medicina Diagnóstica

== Segmento: Saúde
* Gasto per capita com saúde aumentou 29,3% de 2015 a 2019 (ipea 2022/02)
* De R$ 531,8 bilhões passou para R$ 710,4 bilhões
* Crescimento nominal maior nos regimes privados (39,6%) do que nos governamentais (25,5%)

[NOTE.speaker]
--
Isso antes da pandemia de COVID-19.
O mercado de saúde está crescendo e a demanda de serviços de diagnóstico está aumentando.
--

== O maior problema FINANCEIRO da medicina diagnóstica
* São faturamentos não recebidos ou recusados nas organizações de saúde.
* Decorrência de falhas entre o que foi acordado em contrato e o que está descrito nos principais formulários.

[NOTE.speaker]
--
As operadoras de planos de saúde não realizam o pagamento dos custos referentes ao atendimento dos pacientes, 
Isso é chamado de Glosa financeira
--

== Principais motivos de Glosa financeira:
* Falta de clareza na solicitação do exame.
* Falta de anotações ou evoluções incompletas no prontuário.
* Falta de prescrição de medicamentos e procedimentos. 
* Falta de checagem pela enfermagem na prescrição médica.

[NOTE.speaker]
--
Problemas de comunicação entre clínicas e convênios.
--

== Tamanho do Nicho de Mercado
* O percentual de glosa entre operadoras de saúde e laboratórios é de 8.24%.(ANS).

[NOTE.speaker]
--
Isso encarece o custo dos serviços, pois esse prejuizo acaba sendo diluido.
Além disso temos os gastos jurídicos, que são uma forma de tentar recuperar o dinheiro.
--

== Porque Corda R3
* Suporte nativo de contratos inteligentes
* Modelo privado
* Transparência de dados entre os participantes

[NOTE.speaker]
--
Uma lógica de contrato inteligente que permite aos usuários realizar transações usando regras pré-acordadas pelo CorDapps;
Possui eficiência computacional de serviços exclusivos. 
Os serviços podem solicitar transações temporária, o que elimina conflitos;
Possui fluxo de Framework, que simplifica o processo de gravação de protocolos complexos com usuários desconfiados.
--

== Empresa selecionada: DASA
* A Dasa é maior rede de medicina diagnóstica, a segunda maior rede hospitalar do país.
* Líder em medicina diagnóstica no Brasil.
* Também presente na Argentina e Uruguai.
* Possui rede de atendimento conta com mais de 950 unidades.
* Mais de quarenta (40) das marcas mais reconhecidas em diagnósticos no Brasil.
